logging:
  level:
    root: ${logLevel:debug}
spring:
  application:
    name: ${app.name:ping-app}

server:
  port: ${app.port:8080}


spring.datasource:
  continue-on-error: false # Do not stop if an error occurs while initializing the database.
  #data:  # Data (DML) script resource reference.
  initialize: false # Populate the database using 'data.sql'.
  jmx-enabled: false # Enable JMX support (if provided by the underlying pool).
  #jndi-name:  # JNDI location of the datasource. Class, url, username & password are ignored when set.
  max-active: 100
  max-idle: 8
  #max-wait:
  #min-evictable-idle-time-millis:
  min-idle: 8
  name: dataSource # Name of the datasource.
  #platform: all # Platform to use in the schema resource (schema-${platform}.sql).
  #schema:  # Schema (DDL) script resource reference.
  #separator: ; # Statement separator in SQL initialization scripts.
  #sql-script-encoding:  # SQL scripts encoding.
  #test-on-borrow:  # For instance `false`
  #test-on-return:  # For instance `false`
  test-while-idle: true
  time-between-eviction-runs-millis: 1
  validation-query: 'SELECT 1'
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://192.168.56.101:3306/ping_test?useUnicode=true&characterEncoding=utf-8&useSSL=false'
  username: xiaoping
  password: BJ2017@abcd

mybatis:
#  configLocation: classpath:mybatis-config.xml/
#  mapperLocations: classpath:mapper/*.xml,classpath:mapper/*/*.xml # 默认配置
#  basePackage: com.ping.sample # 默认配置application类所在的包

swagger.enable: true

---
spring:
  profiles: env.prod #生产环境配置
  swagger.enable: false

---
spring:
  profiles: env.dev #开发环境配置
  swagger.enable: true

---
spring:
  profiles: env.ci #ci集成环境配置
  swagger.enable: false